hb:
  header:
    brand: HB
    logo_bg: '#712cf9'
    socials:
      github: razonyang/hb
      kofi: razonyang
      paypal: razonyang
      twitter: razonyang
      mastodon: razonyang
  footer:
    socials:
      github: razonyang/hb
      kofi: razonyang
      paypal: razonyang
      twitter: razonyang
      mastodon: razonyang
  blog:
    giscus:
      repo: razonyang/hb-theme
      repo_id: R_kgDOI8nunQ
      category_id: DIC_kwDOI8nunc4CUpCW
